<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
	<key>scope</key>
	<string>source.makefile</string>
	<key>settings</key>
	<dict>
		<key>icon</key>
		<string>makefile</string>
	</dict>
</dict>
</plist>
