import sublime


class UserSyntax:
    def __init__(self, path, name, scope, hidden):
        self.path = path
        self.name = name
        self.scope = scope
        self.hidden = hidden

    def visible_syntaxes_only():
        syntaxes_list_true = []
        all_syntaxes = sublime.list_syntaxes()
        for s in all_syntaxes:
            if s.hidden is not True:
                # print(s.name, s.path)
                syntaxes_list_true.append(s)
        # print(syntaxes_list_true)
        return syntaxes_list_true

    # def build_list():


# # https://www.sublimetext.com/docs/api_reference.html#sublime.Syntax
# # https://www.sublimetext.com/docs/api_reference.html#sublime.list_syntaxes
# # print(sublime.list_syntaxes())
# list_syntaxes = [
#     Syntax(
#         'Packages/PHP/Embeddings/JavaScript (for PHP single-quoted).sublime-syntax',
#         'JavaScript (for PHP single-quoted)',
#         True,
#         'source.js.embedded.string.quoted.single.php',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Python (pytest).sublime-syntax',
#         'Python (pytest)',
#         True,
#         'source.python.pytest',
#     ),
#     Syntax(
#         'Packages/Rails/CSS (Rails).sublime-syntax',
#         'CSS (Rails)',
#         False,
#         'source.css.rails',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Protobuf).sublime-syntax',
#         'Plain Text (Protobuf)',
#         True,
#         'source.proto',
#     ),
#     Syntax(
#         'Packages/Objective-C/Objective-C.sublime-syntax',
#         'Objective-C',
#         False,
#         'source.objc',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/Go (Embedded JS).sublime-syntax',
#         'Go (Embedded JavaScript)',
#         True,
#         'source.go.embedded-backtick-string.js',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Markdown (License).sublime-syntax',
#         'Markdown (License)',
#         True,
#         'text.html.markdown.license',
#     ),
#     Syntax(
#         'Packages/Perl/Embeddings/RegExp (for Perl braces).sublime-syntax',
#         'Regular Expression (Perl inside braces)',
#         True,
#         'source.regexp.perl.braces',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Bun).sublime-syntax',
#         'Binary (Bun)',
#         True,
#         'binary.bun',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Protobuf).sublime-syntax',
#         'Plain Text (Protobuf)',
#         True,
#         'source.proto',
#     ),
#     Syntax(
#         'Packages/OCaml/camlp4.sublime-syntax', 'camlp4', False, 'source.camlp4.ocaml'
#     ),
#     Syntax('Packages/Python/Python.sublime-syntax', 'Python', False, 'source.python'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/INI (tox).sublime-syntax',
#         'INI (tox)',
#         True,
#         'source.ini.tox',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/HTML (Elixir).sublime-syntax',
#         'HTML (Elixir)',
#         True,
#         'text.html.heex',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Jest).sublime-syntax',
#         'JavaScript (Jest)',
#         True,
#         'source.js.jest',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Affinity Designer).sublime-syntax',
#         'Binary (Affinity Designer)',
#         True,
#         'binary.afdesign',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/XML.sublime-syntax',
#         'XML',
#         True,
#         'text.xml',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/HTML (Svelte).sublime-syntax',
#         'HTML (Svelte)',
#         True,
#         'text.html.svelte',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Dockerfile).sublime-syntax',
#         'Plain Text (Dockerfile)',
#         True,
#         'source.dockerfile',
#     ),
#     Syntax(
#         'Packages/Git Formats/Git Rebase.sublime-syntax',
#         'Git Rebase Todo',
#         False,
#         'text.git.rebase',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (WebGPU).sublime-syntax',
#         'Plain Text (WebGPU)',
#         True,
#         'source.wgsl',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/INI (tox).sublime-syntax',
#         'INI (tox)',
#         True,
#         'source.ini.tox',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Kotlin).sublime-syntax',
#         'Plain Text (Kotlin)',
#         True,
#         'source.Kotlin',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Wast).sublime-syntax',
#         'Plain Text (Wast)',
#         True,
#         'text.webassembly',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Prettier).sublime-syntax',
#         'JavaScript (Prettier)',
#         True,
#         'source.js.prettier',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Affinity Photo).sublime-syntax',
#         'Binary (Affinity Photo)',
#         True,
#         'binary.afphoto',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (ESLint).sublime-syntax',
#         'Plain Text (ESLint)',
#         True,
#         'text.plain.eslint',
#     ),
#     Syntax(
#         'Packages/Makefile/Makefile.sublime-syntax',
#         'Makefile',
#         False,
#         'source.makefile',
#     ),
#     Syntax('Packages/CSS/CSS.sublime-syntax', 'CSS', False, 'source.css'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/YAML (Read the Docs).sublime-syntax',
#         'YAML (Read the Docs)',
#         True,
#         'source.yaml.readthedocs',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/RegExp (for PHP).sublime-syntax',
#         'Regular Expressions (PHP)',
#         True,
#         'source.regexp.php',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Markdown (mdx).sublime-syntax',
#         'Markdown (mdx)',
#         True,
#         'text.html.markdown.mdx',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/INI (pytest).sublime-syntax',
#         'INI (pytest)',
#         True,
#         'source.ini.pytest',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/HTML (Svelte).sublime-syntax',
#         'HTML (Svelte)',
#         True,
#         'text.html.svelte',
#     ),
#     Syntax(
#         'Packages/Babel/support/Regular Expressions (JavaScript).sublime-syntax',
#         'Regular Expressions (Javascript)',
#         True,
#         'source.regexp.js',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Git (Docker).sublime-syntax',
#         'Git (Docker)',
#         True,
#         'text.git.ignore.docker',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TypeScript (Jest).sublime-syntax',
#         'TypeScript (Jest)',
#         True,
#         'source.ts.jest',
#     ),
#     Syntax(
#         'Packages/Go/Markdown (Go).sublime-syntax',
#         'Markdown (Go)',
#         False,
#         'text.html.markdown.go',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (CAD).sublime-syntax',
#         'Plain Text (CAD)',
#         True,
#         'text.plain.cad',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Next js).sublime-syntax',
#         'JavaScript (Next js)',
#         True,
#         'source.js.nextjs',
#     ),
#     Syntax('Packages/Lisp/Lisp.sublime-syntax', 'Lisp', False, 'source.lisp'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/HTML (Vue).sublime-syntax',
#         'HTML (Vue)',
#         True,
#         'text.html.vue',
#     ),
#     Syntax(
#         'Packages/ElixirSyntax/syntaxes/HTML (Surface).sublime-syntax',
#         'HTML (Surface)',
#         False,
#         'text.html.surface',
#     ),
#     Syntax(
#         'Packages/Markdown/Markdown.sublime-syntax',
#         'Markdown',
#         False,
#         'text.html.markdown',
#     ),
#     Syntax('Packages/PHP/PHP Source.sublime-syntax', 'PHP Source', True, 'source.php'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Ruby).sublime-syntax',
#         'Plain Text (Ruby)',
#         True,
#         'text.plain.ruby',
#     ),
#     Syntax('Packages/Java/Java.sublime-syntax', 'Java', False, 'source.java'),
#     Syntax(
#         'Packages/OCaml/OCamlyacc.sublime-syntax',
#         'OCamlyacc',
#         False,
#         'source.ocamlyacc',
#     ),
#     Syntax(
#         'Packages/Markdown/Shell (for Markdown).sublime-syntax',
#         'Interactive Unix Shell',
#         True,
#         'source.shell.interactive.markdown',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Microsoft Excel).sublime-syntax',
#         'Binary (Microsoft Excel)',
#         True,
#         'binary.excel',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Vite).sublime-syntax',
#         'JavaScript (Vite)',
#         True,
#         'source.js.vite',
#     ),
#     Syntax(
#         'Packages/Perl/Embeddings/RegExp (for Perl brackets).sublime-syntax',
#         'Regular Expression (Perl inside square brackets)',
#         True,
#         'source.regexp.perl.brackets',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Video).sublime-syntax',
#         'Binary (Video)',
#         True,
#         'binary.video',
#     ),
#     Syntax('Packages/Ruby/Ruby.sublime-syntax', 'Ruby', False, 'source.ruby'),
#     Syntax(
#         'Packages/Rails/HTML (Rails).sublime-syntax',
#         'HTML (Rails)',
#         False,
#         'text.html.rails',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Rspack).sublime-syntax',
#         'JavaScript (Rspack)',
#         True,
#         'source.js.rspack',
#     ),
#     Syntax(
#         'Packages/ElixirSyntax/syntaxes/EEx.sublime-syntax', 'EEx', False, 'text.eex'
#     ),
#     Syntax(
#         'Packages/Git Formats/Git Mailmap.sublime-syntax',
#         'Git Mailmap',
#         False,
#         'text.git.mailmap',
#     ),
#     Syntax(
#         'Packages/Babel/JavaScript (Babel).sublime-syntax',
#         'JavaScript (Babel)',
#         False,
#         'source.js',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/CSS (for PHP single-quoted).sublime-syntax',
#         'CSS (for PHP single-quoted)',
#         True,
#         'source.css.embedded.string.quoted.single.php',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/UnitTest (JavaScript).sublime-syntax',
#         'UnitTest (JavaScript)',
#         True,
#         'source.js.unittest',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/CSS (for Go Embedded Backtick Strings).sublime-syntax',
#         'CSS inside Go backtick string',
#         True,
#         'source.css.go-embedded-backtick-string',
#     ),
#     Syntax(
#         'Packages/PHP/CSS (PHP).sublime-syntax', 'CSS (PHP)', False, 'source.css.php'
#     ),
#     Syntax('Packages/YAML/YAML.sublime-syntax', 'YAML', False, 'source.yaml'),
#     Syntax(
#         'Packages/Rails/Embeddings/Ruby (for HAML).sublime-syntax',
#         'Ruby (for HAML)',
#         True,
#         'source.ruby.rails.embedded.haml',
#     ),
#     Syntax('Packages/User/JS.sublime-syntax', 'JS', False, 'source.js'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Git (ESLint).sublime-syntax',
#         'Git (ESLint)',
#         True,
#         'text.git.ignore.eslint',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Arduino).sublime-syntax',
#         'Plain Text (Arduino)',
#         True,
#         'source.arduino',
#     ),
#     Syntax('Packages/XML/XSL.sublime-syntax', 'XSL', False, 'text.xml.xsl'),
#     Syntax(
#         'Packages/Markdown/MultiMarkdown.sublime-syntax',
#         'MultiMarkdown',
#         False,
#         'text.html.markdown.multimarkdown',
#     ),
#     Syntax(
#         'Packages/Java/Embeddings/Java (for JSP).sublime-syntax',
#         'Java (for JSP)',
#         True,
#         'source.java.embedded.jsp',
#     ),
#     Syntax('Packages/LaTeX/Bibtex.sublime-syntax', 'BibTeX', False, 'text.bibtex'),
#     Syntax(
#         'Packages/Regular Expressions/RegExp.sublime-syntax',
#         'Regular Expression',
#         False,
#         'source.regexp',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/JavaScript (for Go Embedded Backtick Strings).sublime-syntax',
#         'JavaScript (for Go Embedded Backtick Strings)',
#         True,
#         'source.js.go-embedded-backtick-string',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/C++ (Header).sublime-syntax',
#         'C++ (Header)',
#         True,
#         'source.c++.header',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TypeScript (Storybook).sublime-syntax',
#         'TypeScript (Storybook)',
#         True,
#         'source.ts.storybook',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TypeScript (Storybook).sublime-syntax',
#         'TypeScript (Storybook)',
#         True,
#         'source.ts.storybook',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/CSS (for PHP Interpolated).sublime-syntax',
#         'CSS (for PHP Interpolated)',
#         True,
#         'source.css.interpolated.php',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Unity 3D Shader).sublime-syntax',
#         'Plain Text (Unity 3D Shader)',
#         True,
#         'source.shader',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JSON (ESLint).sublime-syntax',
#         'JSON (ESLint)',
#         True,
#         'source.json.eslint',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/UnitTest (TypeScript).sublime-syntax',
#         'UnitTest (TypeScript)',
#         True,
#         'source.ts.unittest',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Settings).sublime-syntax',
#         'Plain Text (Settings)',
#         True,
#         'text.plain.settings',
#     ),
#     Syntax(
#         'Packages/R/R Console.sublime-syntax', 'R Console', False, 'source.r-console'
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (CAD).sublime-syntax',
#         'Plain Text (CAD)',
#         True,
#         'text.plain.cad',
#     ),
#     Syntax(
#         'Packages/JavaScript/Regular Expressions (JavaScript).sublime-syntax',
#         'Regular Expressions (Javascript)',
#         True,
#         'source.regexp.js',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Ruby).sublime-syntax',
#         'Plain Text (Ruby)',
#         True,
#         'text.plain.ruby',
#     ),
#     Syntax('Packages/JavaScript/JSX.sublime-syntax', 'JSX', False, 'source.jsx'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Rspack).sublime-syntax',
#         'JavaScript (Rspack)',
#         True,
#         'source.js.rspack',
#     ),
#     Syntax(
#         'Packages/TCL/HTML (Tcl).sublime-syntax', 'HTML (Tcl)', False, 'text.html.tcl'
#     ),
#     Syntax(
#         'Packages/Rails/SQL (Rails).sublime-syntax',
#         'SQL (Rails)',
#         False,
#         'source.sql.rails',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TypeScript (Rollup).sublime-syntax',
#         'TypeScript (Rollup)',
#         True,
#         'source.ts.rollup',
#     ),
#     Syntax(
#         'Packages/Java/JavaProperties.sublime-syntax',
#         'Java Properties',
#         False,
#         'source.java-props',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (NGINX).sublime-syntax',
#         'Plain Text (NGINX)',
#         True,
#         'source.nginx',
#     ),
#     Syntax(
#         'Packages/Rails/Embeddings/JavaScript (for HAML).sublime-syntax',
#         'JavaScript (for HAML)',
#         True,
#         'source.js.embedded.haml',
#     ),
#     Syntax(
#         'Packages/Rails/Embeddings/CSS (for HAML).sublime-syntax',
#         'CSS (for HAML)',
#         True,
#         'source.css.embedded.haml',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/YAML (for PHP Interpolated).sublime-syntax',
#         'YAML (for PHP Interpolated)',
#         True,
#         'source.yaml.interpolated.php',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/HTML (Vue).sublime-syntax',
#         'HTML (Vue)',
#         True,
#         'text.html.vue',
#     ),
#     Syntax(
#         'Packages/ShellScript/Shell-Unix-Generic.sublime-syntax',
#         'Shell-Unix-Generic',
#         True,
#         'source.shell',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Git Keep.sublime-syntax',
#         'Git Keep',
#         True,
#         'text.git.keep',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (CSV).sublime-syntax',
#         'Plain Text (CSV)',
#         True,
#         'text.csv',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (SCSS).sublime-syntax',
#         'Plain Text (SCSS)',
#         True,
#         'source.scss',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (WebGPU).sublime-syntax',
#         'Plain Text (WebGPU)',
#         True,
#         'source.wgsl',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Sass).sublime-syntax',
#         'Plain Text (Sass)',
#         True,
#         'source.sass',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Jest).sublime-syntax',
#         'JavaScript (Jest)',
#         True,
#         'source.js.jest',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (ESLint).sublime-syntax',
#         'JavaScript (ESLint)',
#         True,
#         'source.js.eslint',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/YAML (Codecov).sublime-syntax',
#         'YAML (Codecov)',
#         True,
#         'source.yaml.codecov',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/PHP Source (for PHP).sublime-syntax',
#         'PHP Source (for PHP)',
#         True,
#         'source.php.embedded.php',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/JavaScript (for PHP double-quoted).sublime-syntax',
#         'JavaScript (for PHP double-quoted)',
#         True,
#         'source.js.embedded.string.quoted.double.php',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/JSON (for Go Embedded Backtick Strings).sublime-syntax',
#         'JSON inside Go backtick string',
#         True,
#         'source.json.go-embedded-backtick-string',
#     ),
#     Syntax(
#         'Packages/Python/Embeddings/RegExp (for Python).sublime-syntax',
#         'Regular Expressions (Python)',
#         True,
#         'source.regexp.python',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/YAML (Read the Docs).sublime-syntax',
#         'YAML (Read the Docs)',
#         True,
#         'source.yaml.readthedocs',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Yarn).sublime-syntax',
#         'JavaScript (Yarn)',
#         True,
#         'source.js.yarn',
#     ),
#     Syntax(
#         'Packages/Git Formats/Git Blame Ignore Revisions.sublime-syntax',
#         'Git Blame Ignore Revisions',
#         False,
#         'text.git.blame.ignorerevs',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TOML (Netlify).sublime-syntax',
#         'TOML (Netlify)',
#         True,
#         'source.toml.netlify',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Storybook).sublime-syntax',
#         'JavaScript (Storybook)',
#         True,
#         'source.js.storybook',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TOML (Poetry).sublime-syntax',
#         'TOML (Poetry)',
#         True,
#         'source.toml.poetry',
#     ),
#     Syntax(
#         'Packages/Rust/Cargo.sublime-syntax',
#         'Cargo Build Results',
#         True,
#         'source.build_results',
#     ),
#     Syntax(
#         'Packages/Objective-C/Objective-C++.sublime-syntax',
#         'Objective-C++',
#         False,
#         'source.objc++',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Git (Prettier).sublime-syntax',
#         'Git (Prettier)',
#         True,
#         'text.git.ignore.prettier',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Archive).sublime-syntax',
#         'Binary (Archive)',
#         True,
#         'binary.archive',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Git Keep.sublime-syntax',
#         'Git Keep',
#         True,
#         'text.git.keep',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Less js).sublime-syntax',
#         'Plain Text (Less js)',
#         True,
#         'source.less',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/JSON (for PHP Interpolated).sublime-syntax',
#         'JSON (for PHP Interpolated)',
#         True,
#         'source.json.interpolated.php',
#     ),
#     Syntax('Packages/User/JSX2.sublime-syntax', 'JSX2', False, 'source.jsx'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/INI (Mypy).sublime-syntax',
#         'INI (Mypy)',
#         True,
#         'source.ini.mypy',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TOML (Cargo).sublime-syntax',
#         'TOML (Cargo)',
#         True,
#         'source.toml.cargo',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/UnitTest (TSX).sublime-syntax',
#         'UnitTest (TSX)',
#         True,
#         'source.tsx.unittest',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/XML (Sublime).sublime-syntax',
#         'XML (Sublime)',
#         True,
#         'text.xml.sublime.snippet',
#     ),
#     Syntax('Packages/HTML/HTML.sublime-syntax', 'HTML', False, 'text.html.basic'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JSON (SWC).sublime-syntax',
#         'JSON (SWC)',
#         True,
#         'source.json.swc',
#     ),
#     Syntax('Packages/Rust/Rust.sublime-syntax', 'Rust', False, 'source.rust'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Shell Script (Node js).sublime-syntax',
#         'Shell Script (Node js)',
#         True,
#         'source.shell.nodejs',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Shell Script (Python).sublime-syntax',
#         'Shell Script (Python)',
#         True,
#         'source.shell.python',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Protobuf).sublime-syntax',
#         'Binary (Protobuf)',
#         True,
#         'binary.proto',
#     ),
#     Syntax(
#         'Packages/Java/Embeddings/CSS (for JSP).sublime-syntax',
#         'CSS (for JSP)',
#         True,
#         'source.css.embedded.jsp',
#     ),
#     Syntax('Packages/User/TSX2.sublime-syntax', 'TSX2', False, 'source.tsx'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/INI (Mypy).sublime-syntax',
#         'INI (Mypy)',
#         True,
#         'source.ini.mypy',
#     ),
#     Syntax('Packages/OCaml/OCaml.sublime-syntax', 'OCaml', False, 'source.ocaml'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Log).sublime-syntax',
#         'Plain Text (Log)',
#         True,
#         'text.plain.log',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JSON (Angular).sublime-syntax',
#         'JSON (Angular)',
#         True,
#         'source.json.angularjs',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Python (pytest).sublime-syntax',
#         'Python (pytest)',
#         True,
#         'source.python.pytest',
#     ),
#     Syntax(
#         'Packages/ElixirSyntax/syntaxes/Elixir (EEx).sublime-syntax',
#         'Elixir (EEx)',
#         False,
#         'source.elixir.eex',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TypeScript (Rspack).sublime-syntax',
#         'TypeScript (Rspack)',
#         True,
#         'source.ts.rspack',
#     ),
#     Syntax(
#         'Packages/ElixirSyntax/syntaxes/HTML (EEx).sublime-syntax',
#         'HTML (EEx)',
#         False,
#         'text.html.eex',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Microsoft Word).sublime-syntax',
#         'Binary (Microsoft Word)',
#         True,
#         'binary.word',
#     ),
#     Syntax(
#         'Packages/Java/Embeddings/Java (for HTML).sublime-syntax',
#         'Java (for HTML)',
#         True,
#         'source.java.embedded.html',
#     ),
#     Syntax(
#         'Packages/RestructuredText/reStructuredText.sublime-syntax',
#         'reStructuredText',
#         False,
#         'text.restructuredtext',
#     ),
#     Syntax(
#         'Packages/Ruby/Embeddings/JavaScript (for Ruby).sublime-syntax',
#         'JavaScript (for Ruby)',
#         True,
#         'source.js.embedded.ruby',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Adobe Illustrator).sublime-syntax',
#         'Binary (Adobe Illustrator)',
#         True,
#         'binary.ai',
#     ),
#     Syntax(
#         'Packages/Rails/JavaScript (Rails).sublime-syntax',
#         'JavaScript (Rails)',
#         False,
#         'source.js.rails',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Webpack).sublime-syntax',
#         'JavaScript (Webpack)',
#         True,
#         'source.js.webpack',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Settings).sublime-syntax',
#         'Plain Text (Settings)',
#         True,
#         'text.plain.settings',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Shell Script (npm).sublime-syntax',
#         'Shell Script (npm)',
#         True,
#         'source.shell.npm',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Autodesk Fusion 360).sublime-syntax',
#         'Binary (Autodesk Fusion 360)',
#         True,
#         'binary.f3d',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JSON (Turbo).sublime-syntax',
#         'JSON (Turbo)',
#         True,
#         'source.json.turbo',
#     ),
#     Syntax(
#         'Packages/Git Formats/Git Config.sublime-syntax',
#         'Git Config',
#         False,
#         'text.git.config',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (SWC).sublime-syntax',
#         'JavaScript (SWC)',
#         True,
#         'source.js.swc',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/YAML (ESLint).sublime-syntax',
#         'YAML (ESLint)',
#         True,
#         'source.yaml.eslint',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (pnpm).sublime-syntax',
#         'JavaScript (pnpm)',
#         True,
#         'source.js.pnpm',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (SWC).sublime-syntax',
#         'JavaScript (SWC)',
#         True,
#         'source.js.swc',
#     ),
#     Syntax(
#         'Packages/Ruby/Embeddings/HTML (for Ruby).sublime-syntax',
#         'HTML (for Ruby)',
#         True,
#         'text.html.embedded.ruby',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Rollup).sublime-syntax',
#         'JavaScript (Rollup)',
#         True,
#         'source.js.rollup',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TOML (Pipenv).sublime-syntax',
#         'TOML (Pipenv)',
#         True,
#         'source.toml.pipenv',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (README).sublime-syntax',
#         'Plain Text (README)',
#         True,
#         'text.plain.readme',
#     ),
#     Syntax('Packages/Diff/Diff.sublime-syntax', 'Diff', False, 'source.diff'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Image).sublime-syntax',
#         'Binary (Image)',
#         True,
#         'binary.image',
#     ),
#     Syntax(
#         'Packages/Batch File/Batch File (Compound).sublime-syntax',
#         'Batch File (Compound)',
#         True,
#         'source.dosbatch.compound',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (CMake).sublime-syntax',
#         'Plain Text (CMake)',
#         True,
#         'source.cmake',
#     ),
#     Syntax(
#         'Packages/Batch File/Batch File.sublime-syntax',
#         'Batch File',
#         False,
#         'source.dosbatch',
#     ),
#     Syntax(
#         'Packages/Perl/Embeddings/RegExp (for Perl).sublime-syntax',
#         'Regular Expression (Perl)',
#         True,
#         'source.regexp.perl',
#     ),
#     Syntax('Packages/JSON/JSON.sublime-syntax', 'JSON', False, 'source.json'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Rollup).sublime-syntax',
#         'JavaScript (Rollup)',
#         True,
#         'source.js.rollup',
#     ),
#     Syntax(
#         'Packages/Git Formats/Git Commit.sublime-syntax',
#         'Git Commit',
#         False,
#         'text.git.commit',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/YAML (Yarn).sublime-syntax',
#         'YAML (Yarn)',
#         True,
#         'source.yaml.yarn',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Vitest).sublime-syntax',
#         'JavaScript (Vitest)',
#         True,
#         'source.js.vitest',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/Go (Embedded XML).sublime-syntax',
#         'Go (Embedded XML)',
#         True,
#         'source.go.embedded-backtick-string.xml',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Git Blame.sublime-syntax',
#         'Git Blame',
#         True,
#         'text.git.blame',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/YAML (Citation).sublime-syntax',
#         'YAML (Citation)',
#         True,
#         'source.yaml.citation',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (ESLint).sublime-syntax',
#         'Plain Text (ESLint)',
#         True,
#         'text.plain.eslint',
#     ),
#     Syntax(
#         'Packages/ElixirSyntax/syntaxes/HTML (HEEx).sublime-syntax',
#         'HTML (HEEx)',
#         False,
#         'text.html.heex',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (OpenGL).sublime-syntax',
#         'Plain Text (OpenGL)',
#         True,
#         'source.glsl',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/icons_syntaxes/Plain Text (README).sublime-syntax',
#         'Plain Text (README)',
#         True,
#         'text.plain.readme',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/UnitTest (JavaScript).sublime-syntax',
#         'UnitTest (JavaScript)',
#         True,
#         'source.js.unittest',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/XML (SVG).sublime-syntax',
#         'XML (SVG)',
#         True,
#         'text.xml.svg',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TypeScript (Vite).sublime-syntax',
#         'TypeScript (Vite)',
#         True,
#         'source.ts.vite',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Shell Script (npm).sublime-syntax',
#         'Shell Script (npm)',
#         True,
#         'source.shell.npm',
#     ),
#     Syntax(
#         'Packages/Git Formats/Git Log.sublime-syntax', 'Git Log', False, 'text.git.log'
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/HTML (for PHP Interpolated).sublime-syntax',
#         'HTML (for PHP Interpolated)',
#         True,
#         'text.html.interpolated.php',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JSON (Jest).sublime-syntax',
#         'JSON (Jest)',
#         True,
#         'source.json.jest',
#     ),
#     Syntax('Packages/R/R.sublime-syntax', 'R', False, 'source.r'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Audio).sublime-syntax',
#         'Binary (Audio)',
#         True,
#         'binary.audio',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (ESLint).sublime-syntax',
#         'JavaScript (ESLint)',
#         True,
#         'source.js.eslint',
#     ),
#     Syntax('Packages/C++/C.sublime-syntax', 'C', False, 'source.c'),
#     Syntax(
#         'Packages/Git Formats/Git Common.sublime-syntax',
#         'Git Common',
#         True,
#         'text.git.common',
#     ),
#     Syntax('Packages/XML/DTD.sublime-syntax', 'DTD', False, 'text.xml.dtd'),
#     Syntax(
#         'Packages/D/DMD Output.sublime-syntax',
#         'DMD Output',
#         True,
#         'source.build_output.dmd',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Unity 3D Shader).sublime-syntax',
#         'Plain Text (Unity 3D Shader)',
#         True,
#         'source.shader',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TSX (Storybook).sublime-syntax',
#         'TSX (Storybook)',
#         True,
#         'source.tsx.storybook',
#     ),
#     Syntax(
#         'Packages/R/Rd (R Documentation).sublime-syntax',
#         'Rd (R Documentation)',
#         False,
#         'text.tex.latex.rd',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/HTML (Elixir).sublime-syntax',
#         'HTML (Elixir)',
#         True,
#         'text.html.heex',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Prettier).sublime-syntax',
#         'JavaScript (Prettier)',
#         True,
#         'source.js.prettier',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Bun).sublime-syntax',
#         'Binary (Bun)',
#         True,
#         'binary.bun',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Shell Script (Node js).sublime-syntax',
#         'Shell Script (Node js)',
#         True,
#         'source.shell.nodejs',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JSON (Sublime).sublime-syntax',
#         'JSON (Sublime)',
#         True,
#         'source.json.sublime',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Markdown (Citation).sublime-syntax',
#         'Markdown (Citation)',
#         True,
#         'text.html.markdown.citation',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JSX (Storybook).sublime-syntax',
#         'JSX (Storybook)',
#         True,
#         'source.jsx.storybook',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/YAML (Sublime).sublime-syntax',
#         'YAML (Sublime)',
#         True,
#         'source.yaml.sublime.syntax',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Webpack).sublime-syntax',
#         'JavaScript (Webpack)',
#         True,
#         'source.js.webpack',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/XML (for Go Embedded Backtick Strings).sublime-syntax',
#         'XML inside Go backtick string',
#         True,
#         'text.xml.go-embedded-backtick-string',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TypeScript (UnoCSS).sublime-syntax',
#         'TypeScript (UnoCSS)',
#         True,
#         'source.ts.unocss',
#     ),
#     Syntax(
#         'Packages/SideBarEnhancements/FindFilesResults.sublime-syntax',
#         'Find Files Results',
#         True,
#         'text.find-in-files',
#     ),
#     Syntax(
#         'Packages/Java/Embeddings/JavaDoc.sublime-syntax',
#         'JavaDoc',
#         True,
#         'text.html.javadoc',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/Go (Embedded JSON).sublime-syntax',
#         'Go (Embedded JSON)',
#         True,
#         'source.go.embedded-backtick-string.json',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/YAML (Sublime).sublime-syntax',
#         'YAML (Sublime)',
#         True,
#         'source.yaml.sublime.syntax',
#     ),
#     Syntax(
#         'Packages/Makefile/Make Output.sublime-syntax',
#         'Make Output',
#         True,
#         'source.build_output',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (License).sublime-syntax',
#         'Plain Text (License)',
#         True,
#         'text.plain.license',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Vite).sublime-syntax',
#         'JavaScript (Vite)',
#         True,
#         'source.js.vite',
#     ),
#     Syntax('Packages/D/D.sublime-syntax', 'D', False, 'source.d'),
#     Syntax(
#         'Packages/PHP/Embeddings/SQL (for PHP Interpolated).sublime-syntax',
#         'SQL (for PHP Interpolated)',
#         True,
#         'source.sql.interpolated.php',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/Go (Embedded SQL).sublime-syntax',
#         'Go (Embedded SQL)',
#         True,
#         'source.go.embedded-backtick-string.sql',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Log).sublime-syntax',
#         'Plain Text (Log)',
#         True,
#         'text.plain.log',
#     ),
#     Syntax('Packages/PHP/PHP.sublime-syntax', 'PHP', False, 'embedding.php'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/XML (Sublime).sublime-syntax',
#         'XML (Sublime)',
#         True,
#         'text.xml.sublime.snippet',
#     ),
#     Syntax('Packages/LaTeX/TeX.sublime-syntax', 'TeX', False, 'text.tex'),
#     Syntax('Packages/Haskell/Cabal.sublime-syntax', 'Cabal', False, 'source.cabal'),
#     Syntax(
#         'Packages/JavaScript/JavaScript.sublime-syntax',
#         'JavaScript',
#         False,
#         'source.js',
#     ),
#     Syntax('Packages/LaTeX/LaTeX.sublime-syntax', 'LaTeX', False, 'text.tex.latex'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (PDF).sublime-syntax',
#         'Binary (PDF)',
#         True,
#         'binary.pdf',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Microsoft Word).sublime-syntax',
#         'Binary (Microsoft Word)',
#         True,
#         'binary.word',
#     ),
#     Syntax(
#         'Packages/Regular Expressions/File Pattern.sublime-syntax',
#         'Sublime File Pattern',
#         True,
#         'source.file-pattern',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Swift).sublime-syntax',
#         'Plain Text (Swift)',
#         True,
#         'source.swift',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Markdown (License).sublime-syntax',
#         'Markdown (License)',
#         True,
#         'text.html.markdown.license',
#     ),
#     Syntax(
#         'Packages/Erlang/HTML (Erlang).sublime-syntax',
#         'HTML (Erlang)',
#         False,
#         'text.html.erlang',
#     ),
#     Syntax('Packages/Perl/Perl.sublime-syntax', 'Perl', False, 'source.perl'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Next js).sublime-syntax',
#         'JavaScript (Next js)',
#         True,
#         'source.js.nextjs',
#     ),
#     Syntax(
#         'Packages/Java/HTML (JSP).sublime-syntax', 'HTML (JSP)', False, 'text.html.jsp'
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Markdown (mdx).sublime-syntax',
#         'Markdown (mdx)',
#         True,
#         'text.html.markdown.mdx',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/SQL (for Go Embedded Backtick Strings).sublime-syntax',
#         'SQL inside Go backtick string',
#         True,
#         'source.sql.go-embedded-backtick-string',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/RegExp (for Go Embedded Backtick Strings).sublime-syntax',
#         'RegExp inside Go backtick string',
#         True,
#         'source.regexp.go-embedded-backtick-string',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/YAML (Yarn).sublime-syntax',
#         'YAML (Yarn)',
#         True,
#         'source.yaml.yarn',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JSON (Babel).sublime-syntax',
#         'JSON (Babel)',
#         True,
#         'source.json.babel',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/YAML (pnpm).sublime-syntax',
#         'YAML (pnpm)',
#         True,
#         'source.yaml.pnpm',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Markdown (README).sublime-syntax',
#         'Markdown (README)',
#         True,
#         'text.html.markdown.readme',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (NGINX).sublime-syntax',
#         'Plain Text (NGINX)',
#         True,
#         'source.nginx',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (License).sublime-syntax',
#         'Plain Text (License)',
#         True,
#         'text.plain.license',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Affinity Publisher).sublime-syntax',
#         'Binary (Affinity Publisher)',
#         True,
#         'binary.afpub',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/YAML (pre-commit).sublime-syntax',
#         'YAML (pre-commit)',
#         True,
#         'source.yaml.precommit',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Dockerfile).sublime-syntax',
#         'Plain Text (Dockerfile)',
#         True,
#         'source.dockerfile',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/UnitTest (TSX).sublime-syntax',
#         'UnitTest (TSX)',
#         True,
#         'source.tsx.unittest',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JSON (ESLint).sublime-syntax',
#         'JSON (ESLint)',
#         True,
#         'source.json.eslint',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Markdown (README).sublime-syntax',
#         'Markdown (README)',
#         True,
#         'text.html.markdown.readme',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Archive).sublime-syntax',
#         'Binary (Archive)',
#         True,
#         'binary.archive',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (UnoCSS).sublime-syntax',
#         'JavaScript (UnoCSS)',
#         True,
#         'source.js.unocss',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/XML (SVG).sublime-syntax',
#         'XML (SVG)',
#         True,
#         'text.xml.svg',
#     ),
#     Syntax('Packages/XML/XML.sublime-syntax', 'XML', False, 'text.xml'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/YAML (Citation).sublime-syntax',
#         'YAML (Citation)',
#         True,
#         'source.yaml.citation',
#     ),
#     Syntax(
#         'Packages/ElixirSyntax/syntaxes/SQL (Elixir).sublime-syntax',
#         'SQL (Elixir)',
#         False,
#         'source.ex.sql',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TOML (Bun).sublime-syntax',
#         'TOML (Bun)',
#         True,
#         'source.toml.bun',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/YAML (pnpm).sublime-syntax',
#         'YAML (pnpm)',
#         True,
#         'source.yaml.pnpm',
#     ),
#     Syntax(
#         'Packages/Regular Expressions/Regex Replace.sublime-syntax',
#         'Regular Expression Replacement',
#         True,
#         'source.regexp-replace',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/C++ (Header).sublime-syntax',
#         'C++ (Header)',
#         True,
#         'source.c++.header',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Go).sublime-syntax',
#         'Plain Text (Go)',
#         True,
#         'source.go',
#     ),
#     Syntax(
#         'Packages/C#/Build.sublime-syntax',
#         'NAnt Build File',
#         False,
#         'source.nant-build',
#     ),
#     Syntax('Packages/Go/Go.sublime-syntax', 'Go', False, 'source.go'),
#     Syntax('Packages/User/TS.sublime-syntax', 'TS', False, 'source.ts'),
#     Syntax(
#         'Packages/Git Formats/Git Link.sublime-syntax',
#         'Git Link',
#         False,
#         'text.git.link',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Git Blame.sublime-syntax',
#         'Git Blame',
#         True,
#         'text.git.blame',
#     ),
#     Syntax(
#         'Packages/LaTeX/LaTeX Log.sublime-syntax', 'LaTeX Log', False, 'text.log.latex'
#     ),
#     Syntax(
#         'Packages/Git Formats/Git Attributes.sublime-syntax',
#         'Git Attributes',
#         False,
#         'text.git.attributes',
#     ),
#     Syntax('Packages/Sass/Syntaxes/Sass.sublime-syntax', 'Sass', False, 'source.sass'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TypeScript (Rspack).sublime-syntax',
#         'TypeScript (Rspack)',
#         True,
#         'source.ts.rspack',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Git (Prettier).sublime-syntax',
#         'Git (Prettier)',
#         True,
#         'text.git.ignore.prettier',
#     ),
#     Syntax(
#         'Packages/Ruby/Embeddings/CSS (for Ruby).sublime-syntax',
#         'CSS (for Ruby)',
#         True,
#         'source.css.embedded.ruby',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/YAML (ESLint).sublime-syntax',
#         'YAML (ESLint)',
#         True,
#         'source.yaml.eslint',
#     ),
#     Syntax(
#         'Packages/Haskell/Literate Haskell.sublime-syntax',
#         'Literate Haskell',
#         False,
#         'text.tex.latex.haskell',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Arduino).sublime-syntax',
#         'Plain Text (Arduino)',
#         True,
#         'source.arduino',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TOML (Ruff).sublime-syntax',
#         'TOML (Ruff)',
#         True,
#         'source.toml.ruff',
#     ),
#     Syntax('Packages/C++/C++.sublime-syntax', 'C++', False, 'source.c++'),
#     Syntax(
#         'Packages/Go/Embeddings/Go (Embedded HTML).sublime-syntax',
#         'Go (Embedded HTML)',
#         True,
#         'source.go.embedded-backtick-string.html',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TypeScript (Rollup).sublime-syntax',
#         'TypeScript (Rollup)',
#         True,
#         'source.ts.rollup',
#     ),
#     Syntax(
#         'Packages/Perl/Embeddings/RegExp (for Perl parens).sublime-syntax',
#         'Regular Expression (Perl inside parens)',
#         True,
#         'source.regexp.perl.parens',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Markdown (Citation).sublime-syntax',
#         'Markdown (Citation)',
#         True,
#         'text.html.markdown.citation',
#     ),
#     Syntax(
#         'Packages/ActionScript/ActionScript.sublime-syntax',
#         'ActionScript',
#         False,
#         'source.actionscript.2',
#     ),
#     Syntax(
#         'Packages/ShellScript/commands-builtin-shell-bash.sublime-syntax',
#         'commands-builtin-shell-bash',
#         True,
#         'commands.builtin.shell.bash',
#     ),
#     Syntax(
#         'Packages/Rails/Embeddings/HTML (for HAML).sublime-syntax',
#         'HTML (for HAML)',
#         True,
#         'text.html.embedded.haml',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (WebAssembly).sublime-syntax',
#         'Binary (WebAssembly)',
#         True,
#         'binary.webassembly',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Image).sublime-syntax',
#         'Binary (Image)',
#         True,
#         'binary.image',
#     ),
#     Syntax(
#         'Packages/ASP/HTML (ASP).sublime-syntax', 'HTML (ASP)', False, 'text.html.asp'
#     ),
#     Syntax('Packages/Groovy/Groovy.sublime-syntax', 'Groovy', False, 'source.groovy'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (PDF).sublime-syntax',
#         'Binary (PDF)',
#         True,
#         'binary.pdf',
#     ),
#     Syntax(
#         'Packages/PHP/JavaScript (PHP).sublime-syntax',
#         'JavaScript (PHP)',
#         False,
#         'source.js.php',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Git (Docker).sublime-syntax',
#         'Git (Docker)',
#         True,
#         'text.git.ignore.docker',
#     ),
#     Syntax('Packages/Binary/Binary.sublime-syntax', 'Binary', True, 'binary.plain'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (Babel).sublime-syntax',
#         'JavaScript (Babel)',
#         True,
#         'source.js.babel',
#     ),
#     Syntax('Packages/Text/Plain text.tmLanguage', 'Plain Text', False, 'text.plain'),
#     Syntax(
#         'Packages/ASP/Embeddings/JavaScript (for ASP).sublime-syntax',
#         'JavaScript (for ASP)',
#         True,
#         'source.js.embedded.asp',
#     ),
#     Syntax(
#         'Packages/Babel/Styled Components.sublime-syntax',
#         'Styled Components',
#         True,
#         'source.js.css',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Shell Script (Ruby).sublime-syntax',
#         'Shell Script (Ruby)',
#         True,
#         'source.shell.ruby',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/icons_syntaxes/Markdown (README).sublime-syntax',
#         'Markdown (README)',
#         True,
#         'text.html.markdown.readme',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Elixir).sublime-syntax',
#         'Plain Text (Elixir)',
#         True,
#         'source.elixir',
#     ),
#     Syntax('Packages/Go/HTML (Go).sublime-syntax', 'HTML (Go)', False, 'text.html.go'),
#     Syntax(
#         'Packages/Ruby/Embeddings/SQL (for Ruby).sublime-syntax',
#         'SQL (for Ruby)',
#         True,
#         'source.sql.embedded.ruby',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Yarn).sublime-syntax',
#         'JavaScript (Yarn)',
#         True,
#         'source.js.yarn',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/HTML (for Go Embedded Backtick Strings).sublime-syntax',
#         'HTML inside Go backtick string',
#         True,
#         'text.html.go-embedded-backtick-string',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Shell Script (Python).sublime-syntax',
#         'Shell Script (Python)',
#         True,
#         'source.shell.python',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JSX (Storybook).sublime-syntax',
#         'JSX (Storybook)',
#         True,
#         'source.jsx.storybook',
#     ),
#     Syntax(
#         'Packages/JavaScript/TypeScript.sublime-syntax',
#         'TypeScript',
#         False,
#         'source.ts',
#     ),
#     Syntax('Packages/SQL/SQL.sublime-syntax', 'SQL', False, 'source.sql'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Microsoft Excel).sublime-syntax',
#         'Binary (Microsoft Excel)',
#         True,
#         'binary.excel',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Markdown (Code of conduct).sublime-syntax',
#         'Markdown (Code of conduct)',
#         True,
#         'text.html.markdown.codeofconduct',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TypeScript (Webpack).sublime-syntax',
#         'TypeScript (Webpack)',
#         True,
#         'source.ts.webpack',
#     ),
#     Syntax(
#         'Packages/Ruby/Embeddings/ShellScript (for Ruby).sublime-syntax',
#         'ShellScript (for Ruby)',
#         True,
#         'source.shell.embedded.ruby',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Affinity Publisher).sublime-syntax',
#         'Binary (Affinity Publisher)',
#         True,
#         'binary.afpub',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TypeScript (Vite).sublime-syntax',
#         'TypeScript (Vite)',
#         True,
#         'source.ts.vite',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (CMake).sublime-syntax',
#         'Plain Text (CMake)',
#         True,
#         'source.cmake',
#     ),
#     Syntax('Packages/Rails/HAML.sublime-syntax', 'HAML', False, 'text.haml'),
#     Syntax(
#         'Packages/Go/Embeddings/Go (Embedded Backtick String).sublime-syntax',
#         'Go (Embedded Backtick String)',
#         True,
#         'source.go.embedded-backtick-string',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JSON (Sublime).sublime-syntax',
#         'JSON (Sublime)',
#         True,
#         'source.json.sublime',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/UnitTest (JSX).sublime-syntax',
#         'UnitTest (JSX)',
#         True,
#         'source.jsx.unittest',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (OpenGL).sublime-syntax',
#         'Plain Text (OpenGL)',
#         True,
#         'source.glsl',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TypeScript (Webpack).sublime-syntax',
#         'TypeScript (Webpack)',
#         True,
#         'source.ts.webpack',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Audio).sublime-syntax',
#         'Binary (Audio)',
#         True,
#         'binary.audio',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/JavaScript (for PHP Interpolated).sublime-syntax',
#         'JavaScript (for PHP Interpolated)',
#         True,
#         'source.js.interpolated.php',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Vitest).sublime-syntax',
#         'JavaScript (Vitest)',
#         True,
#         'source.js.vitest',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TOML (Pipenv).sublime-syntax',
#         'TOML (Pipenv)',
#         True,
#         'source.toml.pipenv',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Kotlin).sublime-syntax',
#         'Plain Text (Kotlin)',
#         True,
#         'source.Kotlin',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Markdown (Code of conduct).sublime-syntax',
#         'Markdown (Code of conduct)',
#         True,
#         'text.html.markdown.codeofconduct',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TOML (Cargo).sublime-syntax',
#         'TOML (Cargo)',
#         True,
#         'source.toml.cargo',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TOML (Ruff).sublime-syntax',
#         'TOML (Ruff)',
#         True,
#         'source.toml.ruff',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JSON (Jest).sublime-syntax',
#         'JSON (Jest)',
#         True,
#         'source.json.jest',
#     ),
#     Syntax('Packages/TCL/Tcl.sublime-syntax', 'Tcl', False, 'source.tcl'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (GraphQL).sublime-syntax',
#         'Plain Text (GraphQL)',
#         True,
#         'source.graphql',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TypeScript (Jest).sublime-syntax',
#         'TypeScript (Jest)',
#         True,
#         'source.ts.jest',
#     ),
#     Syntax(
#         'Packages/Git Formats/Git Code Owners.sublime-syntax',
#         'Git Code Owners',
#         False,
#         'text.git.codeowners',
#     ),
#     Syntax(
#         'Packages/HTML/HTML (Plain).sublime-syntax',
#         'HTML (Plain)',
#         True,
#         'text.html.plain',
#     ),
#     Syntax('Packages/ASP/ASP.sublime-syntax', 'ASP', False, 'source.asp'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Video).sublime-syntax',
#         'Binary (Video)',
#         True,
#         'binary.video',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Babel).sublime-syntax',
#         'JavaScript (Babel)',
#         True,
#         'source.js.babel',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TOML (Bun).sublime-syntax',
#         'TOML (Bun)',
#         True,
#         'source.toml.bun',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Elixir).sublime-syntax',
#         'Plain Text (Elixir)',
#         True,
#         'source.elixir',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TOML (Netlify).sublime-syntax',
#         'TOML (Netlify)',
#         True,
#         'source.toml.netlify',
#     ),
#     Syntax(
#         'Packages/OCaml/OCamllex.sublime-syntax', 'OCamllex', False, 'source.ocamllex'
#     ),
#     Syntax(
#         'Packages/Regular Expressions/RegExp (Basic).sublime-syntax',
#         'Regular Expression (Basic)',
#         True,
#         'source.regexp.basic',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JavaScript (pnpm).sublime-syntax',
#         'JavaScript (pnpm)',
#         True,
#         'source.js.pnpm',
#     ),
#     Syntax(
#         'Packages/Git Formats/Git Commit Message.sublime-syntax',
#         'Git Commit Message',
#         False,
#         'text.git.commit-message',
#     ),
#     Syntax(
#         'Packages/ElixirSyntax/syntaxes/Elixir.sublime-syntax',
#         'Elixir',
#         False,
#         'source.elixir',
#     ),
#     Syntax('Packages/Pascal/Pascal.sublime-syntax', 'Pascal', False, 'source.pascal'),
#     Syntax(
#         'Packages/Go/JavaScript (Go).sublime-syntax',
#         'JavaScript (Go)',
#         False,
#         'source.js.go',
#     ),
#     Syntax(
#         'Packages/Textile/Textile.sublime-syntax', 'Textile', False, 'text.html.textile'
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/XML.sublime-syntax',
#         'XML',
#         True,
#         'text.xml',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JSON (Turbo).sublime-syntax',
#         'JSON (Turbo)',
#         True,
#         'source.json.turbo',
#     ),
#     Syntax(
#         'Packages/Clojure/Clojure.sublime-syntax', 'Clojure', False, 'source.clojure'
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (WebAssembly).sublime-syntax',
#         'Binary (WebAssembly)',
#         True,
#         'binary.webassembly',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Blender).sublime-syntax',
#         'Binary (Blender)',
#         True,
#         'binary.blender',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/Go (Embedded CSS).sublime-syntax',
#         'Go (Embedded CSS)',
#         True,
#         'source.go.embedded-backtick-string.css',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/YAML (Prettier).sublime-syntax',
#         'YAML (Prettier)',
#         True,
#         'source.yaml.prettier',
#     ),
#     Syntax('Packages/Scala/Scala.sublime-syntax', 'Scala', False, 'source.scala'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/YAML (Docker).sublime-syntax',
#         'YAML (Docker)',
#         True,
#         'source.yaml.docker',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/XML (for PHP Interpolated).sublime-syntax',
#         'XML (for PHP Interpolated)',
#         True,
#         'text.xml.interpolated.php',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TypeScript (Next js).sublime-syntax',
#         'TypeScript (Next js)',
#         True,
#         'source.ts.nextjs',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/CSS (for PHP double-quoted).sublime-syntax',
#         'CSS (for PHP double-quoted)',
#         True,
#         'source.css.embedded.string.quoted.double.php',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Adobe Illustrator).sublime-syntax',
#         'Binary (Adobe Illustrator)',
#         True,
#         'binary.ai',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TypeScript (Next js).sublime-syntax',
#         'TypeScript (Next js)',
#         True,
#         'source.ts.nextjs',
#     ),
#     Syntax(
#         'Packages/ShellScript/Bash.sublime-syntax', 'Bash', False, 'source.shell.bash'
#     ),
#     Syntax(
#         'Packages/Java/Embeddings/JavaScript (for JSP).sublime-syntax',
#         'JavaScript (for JSP)',
#         True,
#         'source.js.embedded.jsp',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Affinity Photo).sublime-syntax',
#         'Binary (Affinity Photo)',
#         True,
#         'binary.afphoto',
#     ),
#     Syntax(
#         'Packages/Git Formats/Git Ignore.sublime-syntax',
#         'Git Ignore',
#         False,
#         'text.git.ignore',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/YAML (pre-commit).sublime-syntax',
#         'YAML (pre-commit)',
#         True,
#         'source.yaml.precommit',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Adobe Photoshop).sublime-syntax',
#         'Binary (Adobe Photoshop)',
#         True,
#         'binary.image.ps',
#     ),
#     Syntax(
#         'Packages/Graphviz/DOT.sublime-syntax', 'Graphviz (DOT)', False, 'source.dot'
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Protobuf).sublime-syntax',
#         'Binary (Protobuf)',
#         True,
#         'binary.proto',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TOML (Poetry).sublime-syntax',
#         'TOML (Poetry)',
#         True,
#         'source.toml.poetry',
#     ),
#     Syntax('Packages/C#/C#.sublime-syntax', 'C#', False, 'source.cs'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Shell Script (Ruby).sublime-syntax',
#         'Shell Script (Ruby)',
#         True,
#         'source.shell.ruby',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/YAML (Docker).sublime-syntax',
#         'YAML (Docker)',
#         True,
#         'source.yaml.docker',
#     ),
#     Syntax('Packages/Matlab/Matlab.sublime-syntax', 'MATLAB', False, 'source.matlab'),
#     Syntax(
#         'Packages/PHP/Embeddings/Diff (for PHP Interpolated).sublime-syntax',
#         'Diff (for PHP Interpolated)',
#         True,
#         'source.diff.interpolated.php',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JSON (Angular).sublime-syntax',
#         'JSON (Angular)',
#         True,
#         'source.json.angularjs',
#     ),
#     Syntax(
#         'Packages/Perl/Embeddings/RegExp (for Perl angles).sublime-syntax',
#         'Regular Expression (Perl inside angle brackets)',
#         True,
#         'source.regexp.perl.angles',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TypeScript (Vitest).sublime-syntax',
#         'TypeScript (Vitest)',
#         True,
#         'source.ts.vitest',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TypeScript (UnoCSS).sublime-syntax',
#         'TypeScript (UnoCSS)',
#         True,
#         'source.ts.unocss',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Autodesk Fusion 360).sublime-syntax',
#         'Binary (Autodesk Fusion 360)',
#         True,
#         'binary.f3d',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Go).sublime-syntax',
#         'Plain Text (Go)',
#         True,
#         'source.go',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JSON (SWC).sublime-syntax',
#         'JSON (SWC)',
#         True,
#         'source.json.swc',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (FlatBuffers).sublime-syntax',
#         'Plain Text (FlatBuffers)',
#         True,
#         'source.fbs',
#     ),
#     Syntax(
#         'Packages/ASP/Embeddings/CSS (for ASP).sublime-syntax',
#         'CSS (for ASP)',
#         True,
#         'source.css.embedded.asp',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Wast).sublime-syntax',
#         'Plain Text (Wast)',
#         True,
#         'text.webassembly',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/INI (pytest).sublime-syntax',
#         'INI (pytest)',
#         True,
#         'source.ini.pytest',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (GraphQL).sublime-syntax',
#         'Plain Text (GraphQL)',
#         True,
#         'source.graphql',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/TOML (Prettier).sublime-syntax',
#         'TOML (Prettier)',
#         True,
#         'source.toml.prettier',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Affinity Designer).sublime-syntax',
#         'Binary (Affinity Designer)',
#         True,
#         'binary.afdesign',
#     ),
#     Syntax(
#         'Packages/Rails/Embeddings/Markdown (for HAML).sublime-syntax',
#         'Markdown (for HAML)',
#         True,
#         'text.html.markdown.embedded.haml',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TOML (Prettier).sublime-syntax',
#         'TOML (Prettier)',
#         True,
#         'source.toml.prettier',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (CSV).sublime-syntax',
#         'Plain Text (CSV)',
#         True,
#         'text.csv',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (Storybook).sublime-syntax',
#         'JavaScript (Storybook)',
#         True,
#         'source.js.storybook',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Binary (Blender).sublime-syntax',
#         'Binary (Blender)',
#         True,
#         'binary.blender',
#     ),
#     Syntax('Packages/Lua/Lua.sublime-syntax', 'Lua', False, 'source.lua'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Swift).sublime-syntax',
#         'Plain Text (Swift)',
#         True,
#         'source.swift',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Git (ESLint).sublime-syntax',
#         'Git (ESLint)',
#         True,
#         'text.git.ignore.eslint',
#     ),
#     Syntax(
#         'Packages/Haskell/Haskell.sublime-syntax', 'Haskell', False, 'source.haskell'
#     ),
#     Syntax('Packages/Go/CSS (Go).sublime-syntax', 'CSS (Go)', False, 'source.css.go'),
#     Syntax('Packages/Sass/Syntaxes/SCSS.sublime-syntax', 'SCSS', False, 'source.scss'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TypeScript (Vitest).sublime-syntax',
#         'TypeScript (Vitest)',
#         True,
#         'source.ts.vitest',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JSON (TypeScript).sublime-syntax',
#         'JSON (TypeScript)',
#         True,
#         'source.json.typescript',
#     ),
#     Syntax('Packages/JavaScript/TSX.sublime-syntax', 'TSX', False, 'source.tsx'),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (README).sublime-syntax',
#         'Plain Text (README)',
#         True,
#         'text.plain.readme',
#     ),
#     Syntax('Packages/TOML/TOML.sublime-syntax', 'TOML', False, 'source.toml'),
#     Syntax(
#         'Packages/Makefile/Makefile Shell.sublime-syntax',
#         'Makefile Shell',
#         True,
#         'source.shell.embedded.makefile',
#     ),
#     Syntax(
#         'Packages/Rails/Ruby (Rails).sublime-syntax',
#         'Ruby (Rails)',
#         False,
#         'source.ruby.rails',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (FlatBuffers).sublime-syntax',
#         'Plain Text (FlatBuffers)',
#         True,
#         'source.fbs',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Plain Text (Less js).sublime-syntax',
#         'Plain Text (Less js)',
#         True,
#         'source.less',
#     ),
#     Syntax(
#         'Packages/PHP/Embeddings/SQL (for PHP).sublime-syntax',
#         'SQL (for PHP)',
#         True,
#         'source.sql.embedded.php',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/Binary (Adobe Photoshop).sublime-syntax',
#         'Binary (Adobe Photoshop)',
#         True,
#         'binary.image.ps',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JSON (npm).sublime-syntax',
#         'JSON (npm)',
#         True,
#         'source.json.npm',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JSON (npm).sublime-syntax',
#         'JSON (npm)',
#         True,
#         'source.json.npm',
#     ),
#     Syntax(
#         'Packages/Haskell/Embeddings/HTML (for HSX).sublime-syntax',
#         'HTML (for HSX)',
#         True,
#         'text.html.embedded.haskell',
#     ),
#     Syntax(
#         'Packages/Go/Embeddings/Go (Embedded Regex).sublime-syntax',
#         'Go (Embedded Regex)',
#         True,
#         'source.go.embedded-backtick-string.regexp',
#     ),
#     Syntax(
#         'Packages/AppleScript/AppleScript.sublime-syntax',
#         'AppleScript',
#         False,
#         'source.applescript',
#     ),
#     Syntax(
#         'Packages/ElixirSyntax/syntaxes/PCRE (Erlang).sublime-syntax',
#         'PCRE (Erlang)',
#         True,
#         'source.pcree',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/UnitTest (TypeScript).sublime-syntax',
#         'UnitTest (TypeScript)',
#         True,
#         'source.ts.unittest',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/YAML (Codecov).sublime-syntax',
#         'YAML (Codecov)',
#         True,
#         'source.yaml.codecov',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/examples/sublime-syntax.sublime-syntax',
#         'YAML (Y)',
#         True,
#         'source.y',
#     ),
#     Syntax('Packages/Erlang/Erlang.sublime-syntax', 'Erlang', False, 'source.erlang'),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JSON (TypeScript).sublime-syntax',
#         'JSON (TypeScript)',
#         True,
#         'source.json.typescript',
#     ),
#     Syntax(
#         'Packages/Zukan-Icon-Theme/assets/Zukan Icon Theme/icons_syntaxes/JSON (Babel).sublime-syntax',
#         'JSON (Babel)',
#         True,
#         'source.json.babel',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/YAML (Prettier).sublime-syntax',
#         'YAML (Prettier)',
#         True,
#         'source.yaml.prettier',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/UnitTest (JSX).sublime-syntax',
#         'UnitTest (JSX)',
#         True,
#         'source.jsx.unittest',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/JavaScript (UnoCSS).sublime-syntax',
#         'JavaScript (UnoCSS)',
#         True,
#         'source.js.unocss',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (Sass).sublime-syntax',
#         'Plain Text (Sass)',
#         True,
#         'source.sass',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/Plain Text (SCSS).sublime-syntax',
#         'Plain Text (SCSS)',
#         True,
#         'source.scss',
#     ),
#     Syntax(
#         'Packages/Clojure/ClojureScript.sublime-syntax',
#         'ClojureScript',
#         False,
#         'source.clojure.clojurescript',
#     ),
#     Syntax(
#         'Packages/Zukan Icon Theme/Zukan Icon Theme/icons_syntaxes/TSX (Storybook).sublime-syntax',
#         'TSX (Storybook)',
#         True,
#         'source.tsx.storybook',
#     ),
# ]
