%YAML 1.2
---
name: Makefile
icons:
  - makefile-light
preferences:
  scope: source.makefile
  settings:
    icon: makefile-dark
syntax:
  - name: Makefile
    scope: source.makefile
    hidden: true
    file_extensions:
      - mk
      - mak
      - make
    contexts:
      main: []

# ST Package
