%YAML 1.2
---
name: makefile
preferences:
  scope: source.makefile
  settings:
    icon: makefile
syntax:
  - name: makefile
    scope: source.makefile
    hidden: true
    file_extensions:
      - mk
      - mak
      - make
    contexts:
      main: []

# ST Package
